# Generated by Django 4.1.5 on 2023-01-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=20000)),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
